---
title: Initial Configuration
description: Copies Alatas folders/files, installs dependencies and performs the preliminary configuration
privilege: TrustedInstaller
actions:
    # AME Wizard Live Log for development playbooks
    # Do not change the line position of this, otherwise things will break
  # - !run: {exe: 'cmd.exe', args: '/c start "AME Wizard Live Log" PowerShell -NoP -C "gc -Wait Logs\TIOutput.txt -EA SilentlyContinue | Write-Output; pause"', baseDir: true, wait: false}

    # Prevent annoying notifications during deployment
  - !registryValue: {path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Notifications\Settings\Windows.SystemToast.SecurityAndMaintenance', value: 'Enabled', type: REG_DWORD, data: '0'}

    # Prevent computer from going to sleep during deployment
  - !run: {exe: 'powercfg.exe', args: '/setacvalueindex scheme_current sub_sleep standbyidle 0'}
  - !run: {exe: 'powercfg.exe', args: '/setdcvalueindex scheme_current sub_sleep standbyidle 0'}

  - !writeStatus: {status: 'Copying files'}
  - !cmd:
    command: 'robocopy "AlatasModules" "%windir%\AlatasModules" /E /PURGE /IM /IT /NP > nul'
    weight: 10
    wait: true
    exeDir: true
  - !cmd:
    command: 'robocopy "AlatasDesktop" "%windir%\AlatasDesktop" /E /PURGE /IM /IT /NP > nul'
    weight: 10
    wait: true
    exeDir: true

  - !writeStatus: {status: 'Setting the environment'}
  - !cmd: {command: 'setx PATH "%PATH%;%windir%\AlatasModules;%windir%\AlatasModules\Apps;%windir%\AlatasModules\Other;%windir%\AlatasModules\Tools;%windir%\AlatasModules\Scripts" -m'}
  - !cmd: {command: 'setx PSModulePath "%PSModulePath%;%windir%\AlatasModules\Scripts\Modules" -m'}

    # Doesn't refresh the environment variables of TrustedUninstaller
    # An alternative should be found, for now, exact paths are used
  # - !writeStatus: {status: 'Refreshing variables'}
  # - !run: {exeDir: true, exe: 'REFRESHENV.cmd'}

  ################ NO LOCAL BUILD ################

  - !writeStatus: {status: 'Configuring Optional Features'}
    # Disabled for security purposes
  - !run: {exe: 'DISM.exe', args: '/Online /Disable-Feature /FeatureName:"Internet-Explorer-Optional-amd64" /NoRestart', weight: 30}
  - !run: {exe: 'DISM.exe', args: '/Online /Disable-Feature /FeatureName:"MicrosoftWindowsPowerShellV2" /NoRestart', weight: 30}
  - !run: {exe: 'DISM.exe', args: '/Online /Disable-Feature /FeatureName:"MicrosoftWindowsPowerShellV2Root" /NoRestart', weight: 30}

  - !writeStatus: {status: 'Installing software'}
  - !run:
    exe: 'powershell.exe'
    args: '-NoP -File "SOFTWARE.ps1"'
    exeDir: true
    weight: 150
  - !writeStatus: {status: 'Installing Google Chrome', option: 'browser-chrome'}
  - !run:
    exe: 'powershell.exe'
    args: '-NoP -File "SOFTWARE.ps1" -Chrome'
    exeDir: true
    weight: 150
    option: 'browser-chrome'
  - !writeStatus: {status: 'Installing Brave', option: 'browser-brave'}
  - !run:
    exe: 'powershell.exe'
    args: '-NoP -File "SOFTWARE.ps1" -Brave'
    exeDir: true
    weight: 150
    option: 'browser-brave'

  - !writeStatus: {status: 'Installing LibreWolf', option: 'browser-librewolf'}
  - !run:
    exe: 'powershell.exe'
    args: '-NoP -File LIBREWOLF.ps1'
    exeDir: true
    weight: 150
    option: 'librewolf-winupdater'
  - !run:
    exe: 'powershell.exe'
    args: '-NoP -File "LIBREWOLF.ps1" -NoUpdater'
    exeDir: true
    weight: 150
    option: 'librewolf-winget'

  ################ END NO LOCAL BUILD ################
