---
title: Configure Autologgers
description: Configures and disables unnecessary autologgers for the optimal performance and privacy
privilege: TrustedInstaller
actions:
  # The main purpose and reason of disabling these autologgers is to prevent unncecessary logging
  # and tracking of different applications/components in Windows and prevent them from running at startup
  # as well as in the background. We only disable Windows-related autologgers, not needed for any
  # external applications for logging (such as xperf). They can be viewed in Performance Monitor.

  # https://docs.microsoft.com/en-us/windows/win32/etw/configuring-and-starting-an-autologger-session

  #####################################################################################################

  - !registryValue:
    path: 'HKLM\SYSTEM\CurrentControlSet\Control\WMI\Autologger\Diaglog'
    value: 'Start'
    data: '0'
    type: REG_DWORD
  - !registryValue:
    path: 'HKLM\SYSTEM\CurrentControlSet\Control\WMI\Autologger\Diagtrack-Listener'
    value: 'Start'
    data: '0'
    type: REG_DWORD
