---
title: Enable Windows Photo Viewer
description: Enables and configures the legacy Windows Photo Viewer to be the default for a more familar and lightweight photo viewing experience
privilege: TrustedInstaller
actions:
  - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows Photo Viewer\Capabilities\FileAssociations', value: '.tif', data: 'PhotoViewer.FileAssoc.Tiff', type: REG_SZ}
  - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows Photo Viewer\Capabilities\FileAssociations', value: '.tiff', data: 'PhotoViewer.FileAssoc.Tiff', type: REG_SZ}
  - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows Photo Viewer\Capabilities\FileAssociations', value: '.bmp', data: 'PhotoViewer.FileAssoc.Tiff', type: REG_SZ}
  - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows Photo Viewer\Capabilities\FileAssociations', value: '.dib', data: 'PhotoViewer.FileAssoc.Tiff', type: REG_SZ}
  - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows Photo Viewer\Capabilities\FileAssociations', value: '.gif', data: 'PhotoViewer.FileAssoc.Tiff', type: REG_SZ}
  - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows Photo Viewer\Capabilities\FileAssociations', value: '.jfif', data: 'PhotoViewer.FileAssoc.Tiff', type: REG_SZ}
  - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows Photo Viewer\Capabilities\FileAssociations', value: '.jpe', data: 'PhotoViewer.FileAssoc.Tiff', type: REG_SZ}
  - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows Photo Viewer\Capabilities\FileAssociations', value: '.jpeg', data: 'PhotoViewer.FileAssoc.Tiff', type: REG_SZ}
  - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows Photo Viewer\Capabilities\FileAssociations', value: '.jpg', data: 'PhotoViewer.FileAssoc.Tiff', type: REG_SZ}
  - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows Photo Viewer\Capabilities\FileAssociations', value: '.jxr', data: 'PhotoViewer.FileAssoc.Tiff', type: REG_SZ}
  - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows Photo Viewer\Capabilities\FileAssociations', value: '.png', data: 'PhotoViewer.FileAssoc.Tiff', type: REG_SZ}

  - !registryKey: {path: 'HKCR\PhotoViewer.FileAssoc.Tiff', operation: add}
  - !registryValue: {path: 'HKCR\.tif', value: '', data: 'PhotoViewer.FileAssoc.Tiff', type: REG_SZ}
  - !registryValue: {path: 'HKCR\.tiff', value: '', data: 'PhotoViewer.FileAssoc.Tiff', type: REG_SZ}
  - !registryValue: {path: 'HKCR\.bmp', value: '', data: 'PhotoViewer.FileAssoc.Tiff', type: REG_SZ}
  - !registryValue: {path: 'HKCR\.dib', value: '', data: 'PhotoViewer.FileAssoc.Tiff', type: REG_SZ}
  - !registryValue: {path: 'HKCR\.gif', value: '', data: 'PhotoViewer.FileAssoc.Tiff', type: REG_SZ}
  - !registryValue: {path: 'HKCR\.jfif', value: '', data: 'PhotoViewer.FileAssoc.Tiff', type: REG_SZ}
  - !registryValue: {path: 'HKCR\.jpe', value: '', data: 'PhotoViewer.FileAssoc.Tiff', type: REG_SZ}
  - !registryValue: {path: 'HKCR\.jpeg', value: '', data: 'PhotoViewer.FileAssoc.Tiff', type: REG_SZ}
  - !registryValue: {path: 'HKCR\.jpg', value: '', data: 'PhotoViewer.FileAssoc.Tiff', type: REG_SZ}
  - !registryValue: {path: 'HKCR\.jxr', value: '', data: 'PhotoViewer.FileAssoc.Tiff', type: REG_SZ}
  - !registryValue: {path: 'HKCR\.png', value: '', data: 'PhotoViewer.FileAssoc.Tiff', type: REG_SZ}
