---
title: Disable Core Isolation
description: Disables Core Isolation (VBS) based on the user's options
privilege: TrustedInstaller
actions:
  - !powerShell:
    command: '& """$env:windir\AlatasDesktop\7. Security\Core Isolation (VBS)\Current Configuration.ps1""" -DisableAllVBS'
    exeDir: true
    wait: true
    option: 'vbs-disable'
