---
title: Add Music and Videos folders to Quick Access
description: Adds the 'Music' and 'Videos' folders to Quick Access/Home as they're unpinned by default with recent files being disabled. Win11 fix is available in WIN11.cmd.
privilege: TrustedInstaller
actions:
  - !run:
    exe: 'NSudoLC.exe'
    args: '-U:E -UseCurrentConsole -Wait powershell.exe -NoP -EP Unrestricted -C "$o = new-object -com shell.application; $o.Namespace("""$env:userprofile\Videos""").Self.InvokeVerb(''pintohome''); $o.Namespace("""$env:userprofile\Music""").Self.InvokeVerb(''pintohome'')"'
    exeDir: true
