---
title: Disable Automatic Folder Type Discovery
description: Disables automatic folder type discovery for QoL, as most users would probably want each folder to have the same grid configuration
privilege: TrustedInstaller
actions:
  - !registryKey:
    path: 'HKEY_CURRENT_USER\SOFTWARE\Classes\Local Settings\Software\Microsoft\Windows\Shell\BagMRU'
  - !registryKey:
    path: 'HKEY_CURRENT_USER\SOFTWARE\Classes\Local Settings\Software\Microsoft\Windows\Shell\Bags'
  - !registryValue:
    path: 'HKEY_CURRENT_USER\SOFTWARE\Classes\Local Settings\Software\Microsoft\Windows\Shell\Bags\AllFolders\Shell'
    value: 'FolderType'
    data: 'NotSpecified'
    type: REG_SZ
