---
title: Disable Reserved Bandwidth
description: Disables reserved bandwith for connections for improved network performance
privilege: TrustedInstaller
actions:
    # https://admx.help/?Category=Windows_10_2016&Policy=Microsoft.Policies.QualityofService::QosNonBestEffortLimit
  - !registryValue:
    path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\Psched'
    value: 'NonBestEffortLimit'
    data: '0'
    type: REG_DWORD
